### ISSUE TITLE
"Configured sink is not NSQ"

### ISSUE THREAD

**Issue by lambtron** [snowplow/snowplow-docker#109] opened 2019-02-04 22:44 UTC
when i tried using "stdout", the error message I get in the logs are:

```
 Exception in thread "main" java.lang.IllegalArgumentException: Configured sink is not NSQ
  	at com.snowplowanalytics.snowplow.collectors.scalastream.NsqCollector$.main(NsqCollector.scala:32)
  	at com.snowplowanalytics.snowplow.collectors.scalastream.NsqCollector.main(NsqCollector.scala)
```

probably related to https://github.com/snowplow/snowplow-docker/issues/54. 

parts of my `config.hocon` file (the rest is taken from this [repo's example](https://github.com/snowplow/snowplow-docker/blob/develop/example/scala-stream-collector-config/config.hocon)):

```
sink {
      enabled = stdout
    }
```

what is the necessary config to allow setting to stdout?

**Comment by BenFradet** [comment] 2019-02-05 08:05
hey @lambtron , yes the stdout sink is not provided as a docker image, closing as dupe of #54

**Closed as completed by BenFradet** 2019-02-05 08:05 UTC
